server:
  port: 9000

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/peliculas?serverTimezone=UTC
      username: root
      password: admin1234
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    
